### ISSUE TITLE
Make vscodium compile instead of download

### ISSUE THREAD

**Issue by ImUrX** [wolviecb/overlay#3]
*just an idea for you, would like to help but as the license says "Good luck with that shit"*

**Comment by wolviecb** [comment]
yep, been thinking about that, but couldn't care right now, there's no much gain in building it locally. It follows the same "schema" as the vscode ebuild (which obviously is not built) and I'm fine with it for now. Maybe next winter.

PS: License is a joke, this is a personal overlay as the readme says..
anyway feel free to fork

**Comment by ImUrX** [comment]
the ending part was kind of a joke too ;-;

**Comment by JL2210** [comment]
Isn't this kind of the point of Gentoo? While it could be argued that most of VSCode/ium is just JS, it would be neat to have the parts that are native code be compiled so that it will work on more than just glibc.
